import ExcelJS from "exceljs";
import { Request, Response } from "express";
import fs from "fs";
import path from "path";
import { Database } from "../config/db";

export const getReports = async (req: Request, res: Response) => {
  try {
    const reports = await Database.getReports();
    res.json(reports);
  } catch (error: any) {
    res.status(500).json({ message: "Server error", error: error.message });
  }
};

export const generateReport = async (req: Request, res: Response) => {
  try {
    const { timeframe } = req.body as {
      timeframe: "7d" | "30d" | "90d" | "1yr";
    };

    const endDate = new Date();
    const startDate = new Date();

    switch (timeframe) {
      case "7d":
        startDate.setDate(endDate.getDate() - 7);
        break;
      case "30d":
        startDate.setDate(endDate.getDate() - 30);
        break;
      case "90d":
        startDate.setDate(endDate.getDate() - 90);
        break;
      case "1yr":
        startDate.setFullYear(endDate.getFullYear() - 1);
        break;
      default:
        throw new Error("Invalid timeframe");
    }

    const dateRange = {
      start: startDate.toISOString().split("T")[0],
      end: endDate.toISOString().split("T")[0],
    };

    const data = await Database.getKeyMetrics(
      req.user!.role,
      req.user!.id,
      timeframe
    );
    const userId = req.user?.id as number;

    const reportsDir = path.join(__dirname, "../uploads/reports");
    if (!fs.existsSync(reportsDir)) {
      fs.mkdirSync(reportsDir, { recursive: true });
    }

    const fileName = `report_${timeframe}_${Date.now()}.xlsx`;
    const filePath = path.join(reportsDir, fileName);

    const workbook = new ExcelJS.Workbook();
    workbook.creator = "Dashboard System";
    workbook.created = new Date();

    const summary = workbook.addWorksheet("Summary");
    summary.columns = [
      { header: "Field", key: "field", width: 30 },
      { header: "Value", key: "value", width: 50 },
    ];
    summary.addRows([
      { field: "Timeframe", value: timeframe },
      { field: "Date Range", value: `${dateRange.start} - ${dateRange.end}` },
      { field: "Generated By User ID", value: userId },
    ]);

    for (const [section, items] of Object.entries(data)) {
      const sheet = workbook.addWorksheet(section);
      sheet.columns = [
        { header: "Label", key: "label", width: 30 },
        { header: "Value", key: "value", width: 30 },
      ];
      sheet.addRows(items);
    }

    await workbook.xlsx.writeFile(filePath);

    const stats = fs.statSync(filePath);
    const relativeFilePath = `uploads/reports/${fileName}`;

    const report = await Database.saveReportToDB(
      fileName,
      "excel",
      relativeFilePath,
      stats.size,
      userId,
      dateRange
    );

    res.json({ success: true, report });
  } catch (error: any) {
    console.error(error);
    res.status(500).json({
      success: false,
      message: "Failed to generate Excel report",
      error: error.message,
    });
  }
};

export const generateUserReport = async (req: Request, res: Response) => {
  try {
    const { rows, total } = await Database.getAllUsersNoFilter();
    const userId = req.user?.id as number;

    const reportsDir = path.join(__dirname, "../uploads/reports");
    if (!fs.existsSync(reportsDir)) {
      fs.mkdirSync(reportsDir, { recursive: true });
    }

    const fileName = `user_report_${Date.now()}.xlsx`;
    const filePath = path.join(reportsDir, fileName);

    const workbook = new ExcelJS.Workbook();
    workbook.creator = "Dashboard System";
    workbook.created = new Date();

    const summary = workbook.addWorksheet("Summary");
    summary.columns = [
      { header: "Field", key: "field", width: 30 },
      { header: "Value", key: "value", width: 50 },
    ];
    summary.addRows([
      { field: "Total Users", value: total },
      { field: "Generated By User ID", value: userId },
      { field: "Generated At", value: new Date().toISOString() },
    ]);

    const usersSheet = workbook.addWorksheet("Users");
    usersSheet.columns = [
      { header: "ID", key: "id", width: 10 },
      { header: "Name", key: "name", width: 20 },
      { header: "Username", key: "username", width: 20 },
      { header: "Email", key: "email", width: 30 },
      { header: "Phone", key: "phone", width: 15 },
      { header: "Status", key: "status", width: 15 },
      { header: "Role", key: "role", width: 15 },
      { header: "Current Balance", key: "current_balance", width: 20 },
      { header: "Total Earned", key: "total_earned", width: 20 },
      { header: "Ads Watched", key: "ads_watched_count", width: 15 },
      { header: "Last Active", key: "last_active_at", width: 25 },
      { header: "Created At", key: "created_at", width: 25 },
      { header: "Updated At", key: "updated_at", width: 25 },
      { header: "IP Address", key: "ip_address", width: 20 },
      { header: "Location", key: "location", width: 20 },
      { header: "Gender", key: "gender", width: 10 },
    ];

    usersSheet.addRows(rows);

    await workbook.xlsx.writeFile(filePath);

    const stats = fs.statSync(filePath);
    const relativeFilePath = `uploads/reports/${fileName}`;

    const report = await Database.saveReportToDB(
      fileName,
      "user_report",
      relativeFilePath,
      stats.size,
      userId
    );

    res.json({ success: true, report });
  } catch (error: any) {
    console.error(error);
    res.status(500).json({
      success: false,
      message: "Failed to generate Excel report",
      error: error.message,
    });
  }
};

export const generateFinancialReport = async (req: Request, res: Response) => {
  try {
    const { timeframe } = req.body;
    const userId = req.user?.id as number;

    const metrics = await Database.getFinancialOverview(
      req.user!.role,
      userId,
      timeframe
    );

    const reportsDir = path.join(__dirname, "../uploads/reports");
    if (!fs.existsSync(reportsDir)) {
      fs.mkdirSync(reportsDir, { recursive: true });
    }

    const fileName = `financial_report_${Date.now()}.xlsx`;
    const filePath = path.join(reportsDir, fileName);

    const workbook = new ExcelJS.Workbook();
    workbook.creator = "Dashboard System";
    workbook.created = new Date();

    const summary = workbook.addWorksheet("Summary");
    summary.columns = [
      { header: "Field", key: "field", width: 30 },
      { header: "Value", key: "value", width: 50 },
    ];
    summary.addRows([
      { field: "Timeframe", value: timeframe },
      { field: "Generated By User ID", value: userId },
      { field: "Generated At", value: new Date().toISOString() },
    ]);

    const financialSheet = workbook.addWorksheet("Financial Overview");
    financialSheet.columns = [
      { header: "Label", key: "label", width: 30 },
      { header: "Value", key: "value", width: 30 },
    ];
    financialSheet.addRows(metrics);

    await workbook.xlsx.writeFile(filePath);

    const stats = fs.statSync(filePath);
    const relativeFilePath = `uploads/reports/${fileName}`;

    const report = await Database.saveReportToDB(
      fileName,
      "financial_report",
      relativeFilePath,
      stats.size,
      userId
    );

    res.json({ success: true, report });
  } catch (error: any) {
    console.error(error);
    res.status(500).json({
      success: false,
      message: "Failed to generate financial Excel report",
      error: error.message,
    });
  }
};

export const generateAdAnalyticsReport = async (
  req: Request,
  res: Response
) => {
  try {
    const { timeframe } = req.body;
    const metrics = await Database.getAdPerformance(
      req.user!.role,
      req.user!.id,
      timeframe
    );
    const userId = req.user?.id as number;

    const reportsDir = path.join(__dirname, "../uploads/reports");
    if (!fs.existsSync(reportsDir)) {
      fs.mkdirSync(reportsDir, { recursive: true });
    }

    const fileName = `ad_analytics_report_${Date.now()}.xlsx`;
    const filePath = path.join(reportsDir, fileName);

    const workbook = new ExcelJS.Workbook();
    workbook.creator = "Dashboard System";
    workbook.created = new Date();

    const summary = workbook.addWorksheet("Summary");
    summary.columns = [
      { header: "Field", key: "field", width: 30 },
      { header: "Value", key: "value", width: 50 },
    ];
    summary.addRows([
      { field: "Generated By User ID", value: userId },
      { field: "Generated At", value: new Date().toISOString() },
    ]);

    if (metrics) {
      const metricsSheet = workbook.addWorksheet("Ad Metrics");
      metricsSheet.columns = [
        { header: "Metric", key: "metric", width: 30 },
        { header: "Value", key: "value", width: 30 },
      ];

      Object.values(metrics).forEach((metric: any) => {
        metricsSheet.addRow({ metric: metric.label, value: metric.value });
      });
    }

    await workbook.xlsx.writeFile(filePath);

    const stats = fs.statSync(filePath);
    const relativeFilePath = `uploads/reports/${fileName}`;

    const report = await Database.saveReportToDB(
      fileName,
      "ad_analytics_report",
      relativeFilePath,
      stats.size,
      userId
    );

    res.json({ success: true, report });
  } catch (error: any) {
    console.error(error);
    res.status(500).json({
      success: false,
      message: "Failed to generate Ad Analytics report",
      error: error.message,
    });
  }
};
